# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"

    - PYTHON: "C:\\Python38"
      TOX_ENV: "py38"

    - PYTHON: "C:\\Python39"
      TOX_ENV: "py39"

init:
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print( 8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install tox"
  - "%PYTHON%/Scripts/pip install wheel"
  - "%PYTHON%/Scripts/pip install psutil"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox -e %TOX_ENV%"

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
